id=avro-validation
name=AVRO Validation
version=${project.version}
description=${project.description}
class=io.gravitee.avrovalidation.AvroValidationPolicy
type=policy
category=others
icon=avro-validation.svg
native_kafka=PUBLISH,SUBSCRIBE
